export const dataProjects = [
	{
		id: 1,
		name: "Results summary component",
		link: "./src/projects/1_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img1.png",
		video: "https://youtu.be/dm621Ag7h0A",
	},
	{
		id: 2,
		name: "Product preview card component",
		link: "./src/projects/2_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img2.png",
		video: "https://youtu.be/OZWkZFhUNOs",
	},
	{
		id: 3,
		name: "QR code componentc frontendmentor",
		link: "./src/projects/3_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img3.png",
		video: "https://youtu.be/W1oVTnidxo4",
	},
	{
		id: 4,
		name: "NFT preview card component",
		link: "./src/projects/4_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img4.png",
		video: "https://youtu.be/9gmjOsLwlIg",
	},
	{
		id: 5,
		name: "Order summary component",
		link: "./src/projects/5_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img5.png",
		video: "https://youtu.be/V6EPloigfpY",
	},
];
