export const dataProjects = [
	{
		id: 1,
		name: "Results summary component",
		link: "./src/projects/1_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img1.png",
		video: "https://youtu.be/dm621Ag7h0A",
	},
	{
		id: 2,
		name: "Product preview card component",
		link: "./src/projects/2_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img2.png",
		video: "https://youtu.be/OZWkZFhUNOs",
	},
	{
		id: 3,
		name: "QR code componentc frontendmentor",
		link: "./src/projects/3_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img3.png",
		video: "https://youtu.be/W1oVTnidxo4",
	},
	{
		id: 4,
		name: "NFT preview card component",
		link: "./src/projects/4_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img4.png",
		video: "https://youtu.be/9gmjOsLwlIg",
	},
	{
		id: 5,
		name: "Order summary component",
		link: "./src/projects/5_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img5.png",
		video: "https://youtu.be/V6EPloigfpY",
	},
	{
		id: 6,
		name: "Stats preview card component main",
		link: "./src/projects/6_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img6.png",
		video: "https://youtu.be/9C3dfC9fQxo",
	},
	{
		id: 7,
		name: "3 column preview card component main",
		link: "./src/projects/7_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img7.png",
		video: "https://youtu.be/woQ3TSBkrdg",
	},
	{
		id: 8,
		name: "Profile card component main",
		link: "./src/projects/8_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img8.png",
		video: "https://youtu.be/qjnQjR_bs_4",
	},
	{
		id: 9,
		name: "Social-proof-section-master",
		link: "./src/projects/9_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img9.png",
		video: "https://youtu.be/PbTOuXoIeHw",
	},
	{
		id: 10,
		name: "Four card feature section master",
		link: "./src/projects/10_project",
		tags: ["css", "html"],
		nivel: "Newbie",
		img: "./src/images/img10.png",
		video: "https://youtu.be/y4eiouLU984",
	},
];
